# Site settings
title:          Ryan Kim
description:    "My Sandbox"
url:            "https://k2hcorp.github.io"

# Author
author:
  name:         Ryan Kihwan Kim
  url:          https://k2hcorp.github.io
  email:        k2hcorp@gmail.com

# Build settings
markdown:       kramdown

# Assets
sass:
  sass_dir:     _sass
  style:        compressed

permalink:    /:year-:month-:day/:title
paginate:     5

# Gems
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-remote-theme
  - jekyll-seo-tag
  # - jemoji #Uncomment this to allow emoji in your post

# Server Config
livereload: true     # You no longer need to include --livereload

# Permalinks
permalink:      /:year-:month-:day/:title
paginate:       5
